---
- name: Install Nginx
  apt:
    name: nginx
    state: latest

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_file }}"
  notify: Restart Nginx

- name: Start Nginx
  service:
    name: nginx
    state: started

- name: Adding a bad role
  test: This looks wrong and I want code bot to fix it.
